### ISSUE TITLE
ModuleNotFoundError: No module named 'suricatalog.ui'

### ISSUE THREAD

**Issue by andrewhack** [josevnz/SuricataLog#6]
Hi,
I am receiving an error. This is a fresh install (virtenv) on Debian 12

Traceback (most recent call last):
  File "/root/virtualenv/suricatalog/bin/eve_log.py", line 10, in <module>
    from suricatalog.ui.app import EveLogApp
ModuleNotFoundError: No module named 'suricatalog.ui'

**Comment by josevnz** [comment]
Hi. What commands did you execute to install this? Also what version of Linux and Python do you use?

**Comment by josevnz** [comment]
I erased my previous comment . Yes, I can reproduce your error, will release a fix over the weekend:

```shell
[josevnz@dmaf5 ~]$ python3 -m venv ~/virtualenv/suricatalog
[josevnz@dmaf5 ~]$ . ~/virtualenv/suricatalog/bin/activate
(suricatalog) [josevnz@dmaf5 ~]$ python3 -m pip install --upgrade pip setuptools wheel
Requirement already satisfied: pip in ./virtualenv/suricatalog/lib64/python3.11/site-packages (22.2.2)
Collecting pip
  Downloading pip-23.2.1-py3-none-any.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 13.2 MB/s eta 0:00:00
Requirement already satisfied: setuptools in ./virtualenv/suricatalog/lib64/python3.11/site-packages (62.6.0)
Collecting setuptools
  Downloading setuptools-68.1.2-py3-none-any.whl (805 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 805.1/805.1 kB 14.8 MB/s eta 0:00:00
Collecting wheel
  Downloading wheel-0.41.2-py3-none-any.whl (64 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.8/64.8 kB 10.5 MB/s eta 0:00:00
Installing collected packages: wheel, setuptools, pip
  Attempting uninstall: setuptools
    Found existing installation: setuptools 62.6.0
    Uninstalling setuptools-62.6.0:
      Successfully uninstalled setuptools-62.6.0
  Attempting uninstall: pip
    Found existing installation: pip 22.2.2
    Uninstalling pip-22.2.2:
      Successfully uninstalled pip-22.2.2
Successfully installed pip-23.2.1 setuptools-68.1.2 wheel-0.41.2
(suricatalog) [josevnz@dmaf5 ~]$ pip3 install --upgrade SuricataLog
Collecting SuricataLog
  Downloading SuricataLog-0.0.7-py3-none-any.whl (14 kB)
Collecting rich (from SuricataLog)
  Obtaining dependency information for rich from https://files.pythonhosted.org/packages/8d/5f/21a93b2ec205f4b79853ff6e838e3c99064d5dbe85ec6b05967506f14af0/rich-13.5.2-py3-none-any.whl.metadata
  Downloading rich-13.5.2-py3-none-any.whl.metadata (18 kB)
Collecting textual==0.1.18 (from SuricataLog)
  Using cached textual-0.1.18-py3-none-any.whl (89 kB)
Collecting rich (from SuricataLog)
  Using cached rich-12.6.0-py3-none-any.whl (237 kB)
Collecting commonmark<0.10.0,>=0.9.0 (from rich->SuricataLog)
  Using cached commonmark-0.9.1-py2.py3-none-any.whl (51 kB)
Collecting pygments<3.0.0,>=2.6.0 (from rich->SuricataLog)
  Obtaining dependency information for pygments<3.0.0,>=2.6.0 from https://files.pythonhosted.org/packages/43/88/29adf0b44ba6ac85045e63734ae0997d3c58d8b1a91c914d240828d0d73d/Pygments-2.16.1-py3-none-any.whl.metadata
  Downloading Pygments-2.16.1-py3-none-any.whl.metadata (2.5 kB)
Downloading Pygments-2.16.1-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 9.8 MB/s eta 0:00:00
Installing collected packages: commonmark, pygments, rich, textual, SuricataLog
Successfully installed SuricataLog-0.0.7 commonmark-0.9.1 pygments-2.16.1 rich-12.6.0 textual-0.1.18

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
(suricatalog) [josevnz@dmaf5 ~]$ python -m unittest test^Cest_suricatalog.py
(suricatalog) [josevnz@dmaf5 ~]$ pwd
/home/josevnz
(suricatalog) [josevnz@dmaf5 ~]$ eve_log.py 
Traceback (most recent call last):
  File "/home/josevnz/virtualenv/suricatalog/bin/eve_log.py", line 10, in <module>
    from suricatalog.ui.app import EveLogApp
ModuleNotFoundError: No module named 'suricatalog.ui'

```

**Comment by josevnz** [comment]
Released fix, uploaded new module to Pypi:

https://pypi.org/project/SuricataLog/

**Comment by andrewhack** [comment]
still not working - different error

![image](https://github.com/josevnz/SuricataLog/assets/46722365/fde343dc-7e18-436d-b0dd-7fdd62d3d324)

**Comment by josevnz** [comment]
I cannot reproduce this error, works on my setup. Can you please open a new issue with the following:

1. How did you install it (full command)
2. Full version of Python and installation (System Python, Anaconda, ?. ```python -v```). 
3. OS name and kernel (```uname -a```)
4. What command where you trying to run (full command line please, example eve_log $blah)
5. Output of pip freeze, like ```. ~/virtualenv/bin/activate && pip freeze```

I do see from the traces and your comments that you use Debian and Python 3.11.  My base setup is Fedora 37 with Python 3.11 and I do not see the issue, I do not run this as root tough (but that should not make a difference).

Not re-opening this issue as your problem seems to be something different. I suspect it could be an issue with textual and I may need to update the code (API changed a lot with the recent version but is worth trying).

--Jose

**Comment by andrewhack** [comment]
. ~/virtualenv/suricatalog/bin/activate; pip3 install --upgrade SuricataLog
Python 3.11.2
Linux host 6.1.0-11-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.38-4 (2023-08-08) x86_64 GNU/Linux
eve_log.py --timestamp '2015-01-01 10:41:21.642899' --formats table /var/log/suricata/eve.json

. ~/virtualenv/suricatalog/bin/activate && pip freeze
commonmark==0.9.1
Pygments==2.16.1
rich==12.4.4
SuricataLog==0.0.8
textual==0.1.18

**Comment by josevnz** [comment]
Uploaded new module to Pypi, tested my changes with your data file and mine on several platforms:

```shell
(SuricataLog) [josevnz@dmaf5 SuricataLog]$ twine upload dist/SuricataLog-0.1.0-py3-none-any.whl 
Uploading distributions to https://upload.pypi.org/legacy/
Uploading SuricataLog-0.1.0-py3-none-any.whl
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB • 00:00 • 24.6 MB/s

View at:
https://pypi.org/project/SuricataLog/0.1.0/
```
